#
# Copyright The Titan Project Contributors.
#

#
# On creating a new tag, we publish our maven artifacts to the titan maven bucket.
#
name: Release

on: create

jobs:
  publish:
    name: Test and publish
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
